language: node_js
node_js:
   - "4.*"

branches:
  only:
    - master
    - dev
script:
  make riot

sudo: false

install:
  - npm i jade
  - npm i babel@5.8
  - npm i coffee-script
  - npm i livescript
  - npm i typescript-simple
  - npm i stylus
  - npm i nib
  - npm i node-sass
  - npm install

after_success:
  make test-coveralls && make test-sauce

notifications:
    email: false
