language: node_js
node_js:
  - 6

branches:
  only:
    - master
    - dev
    - next

script:
  make riot

sudo: false

after_success:
  test $TRAVIS_BRANCH" != "next" && test $TRAVIS_PULL_REQUEST == "false"  && make test-sauce && make test-coveralls

notifications:
    email: false
