language: node_js
node_js:
   - "4.*"

branches:
  only:
    - master
    - dev
script:
  make riot

sudo: false

before_install:
  npm install babel && npm install jade && npm install coffee-script && npm install stylus && npm install nib && npm install node-sass && npm install

after_success:
  make test-sauce && make test-coveralls

notifications:
    email: false
