language: node_js
node_js:
  - 6

branches:
  only:
    - master
    - dev
    - next

script:
  make riot

sudo: false

after_success:
  if [ "$TRAVIS_BRANCH" != "next" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    make test-sauce && make test-coveralls || false'
  fi

notifications:
    email: false
